### ISSUE TITLE
Not an issue but info.

### ISSUE THREAD

**Issue by qsrahman** [palladian1/xv6-annotated#2]
Hi
Will there be any future updates to this excellent xv6 commentary?
thx

**Comment by spamegg1** [comment]
@qsrahman I hope so! I believe @palladian is quite busy. They were working on a tough project rewriting `xv6` in Rust, also possibly looking into changing jobs. It might be a while before they are back. I was also gone for a few months.

**Comment by qsrahman** [comment]
@spamegg1 thanks. Hope all go well for both of you.
